model1:
  input_size: 2352
  hidden_size: [1600]
  output_size: 10

model2:
  input_size: 2352
  hidden_size: [2000,1000]
  output_size: 10

model3:
  input_size: 2352
  hidden_size: [2000,1000,500]
  output_size: 10