model1:
  input_size: 2352
  hidden_size: [2000,1000,500]
  output_size: 10

model2:
  input_size: 2352
  hidden_size: [2000,2000,1000]
  output_size: 10

model3:
  input_size: 2352
  hidden_size: [2000,900,400]
  output_size: 10

model4:
  input_size: 2352
  hidden_size: [2000,2000,2000]
  output_size: 10

model5:
  input_size: 2352
  hidden_size: [1000,1000,500]
  output_size: 10