model1:
  input_size: 441
  hidden_size: [40]
  output_size: 10

model2:
  input_size: 441
  hidden_size: [60,40]
  output_size: 10

model3:
  input_size: 441
  hidden_size: [160,80,40]
  output_size: 10

model4:
  input_size: 441
  hidden_size: [200,100,50]
  output_size: 10

model5:
  input_size: 441
  hidden_size: [240,120,60]
  output_size: 10

model6:
  input_size: 441
  hidden_size: [320,160,80]
  output_size: 10

model7:
  input_size: 441
  hidden_size: [400,200,100]
  output_size: 10

model8:
  input_size: 441
  hidden_size: [120,80,40,20]
  output_size: 10

model9:
  input_size: 441
  hidden_size: [200,150,100,50]
  output_size: 10

model10:
  input_size: 441
  hidden_size: [300,150,100,50]
  output_size: 10